# Generated by Django 4.2.7 on 2025-11-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationresult',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
